[project]
name = "ai-engineering-buildcamp-codespaces"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "shally", email = "shallysubhash@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "jupyter>=1.1.1",
    "openai>=3.22.1",
]

[project.scripts]
ai-engineering-buildcamp-codespaces = "ai_engineering_buildcamp_codespaces:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"
